StationWare/stationware

Resources/Maps/stationware.yml, Resources/Prototypes/Entities/_StationWare/Structures/structures.yml
bus is el sexo
Closes #3 
**Media**
**Changelog**
no cl no fun
=> Bus Revamp

Content.Server/_StationWare/WareEvents/Components/AddHandWareEventComponent.cs, Content.Server/_StationWare/WareEvents/Components/MoveSpeedWareEventComponent.cs, Content.Server/_StationWare/WareEvents/Events/AddHandWareEvent.cs, Content.Server/_StationWare/WareEvents/Events/GiveItemWareEvent.cs, Content.Server/_StationWare/WareEvents/Events/MoveSpeedWareEvent.cs, Content.Server/_StationWare/WareEvents/Events/PolymorphWareEvent.cs, Content.Server/_StationWare/WareEvents/WareEventSystem.cs, Content.Shared/_StationWare/WareEvents/WareEvent.cs, Resources/Locale/en-US/_StationWare/ware-events/ware_events.ftl, Resources/Prototypes/GameRules/_StationWare/ware_events.yml
polymorph, movement speed, hands
adds a few in-game events for each.
**Media**
**Changelog**
no cl no fun.
=> 3 new event types

Content.Server/_StationWare/StationEvents/WareEventSchedulerSystem.cs, Content.Shared/CCVar/CCVars.cs
figured this would be cool for admemes
Closes #13
**Media**
**Changelog**
no cl no fun
=> add a cvar for wareevent interval

Content.IntegrationTests/Tests/PostMapInitTest.cs
no webedits allowed
this should be a mild speedup (or rather just not doing shit we don't have to do)
**Media**
**Changelog**
no cl no fun
=> actually fix postmapinittest

Content.Server/_StationWare/Mobs/DeleteOnDeathSystem.cs, Content.Shared/CCVar/CCVars.cs, Resources/Prototypes/Entities/_StationWare/Structures/structures.yml
Closes #12 
**Media**
**Changelog**
no cl no fun
=> Delete bodies on death, fix structure names/descs

Resources/Locale/en-US/_StationWare/ware-events/challenges.ftl, Resources/Prototypes/Challenges/challenges.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Ammunition/Cartridges/pistol.yml, Resources/Prototypes/Entities/Objects/Weapons/Guns/Pistols/stationware_pistols.yml
Closes #20 
**Media**
**Changelog**
no cl no fun
=> Gun with one bullet challenge

Content.Server/_StationWare/Challenges/Modifiers/Components/FreezeModifierComponent.cs, Content.Server/_StationWare/Challenges/Modifiers/Systems/FreezeModifierSystem.cs, Resources/Locale/en-US/_StationWare/ware-events/challenges.ftl, Resources/Prototypes/Challenges/challenges.yml
Closes #42 
If you move you lose.
Don't move.
:)
**Media**
**Changelog**
no cl no fun
=> Freeze Challenge

Content.Server/_StationWare/Challenges/Modifiers/Systems/StayOnGridModifierSystem.cs
i returned inside a loop.
Closes #60 
**Media**
**Changelog**
no cl no fun
=> fix not-spleef not always working

Content.Server/_StationWare/GameRules/StationWareRuleSystem.cs
Fixes name duplication in the menu, point resetting bug, and adds a 10 second post round period.
post-round deathmatch can be added later when i'm not lazy and wanting to get bugs done.
Closes #59 
Closes #68 
Closes #67 
**Media**
**Changelog**
no cl no fun
=> Gamerule tweaks

Resources/ConfigPresets/_StationWare/stationware.toml, Resources/ConfigPresets/_StationWare/uswest.toml
Modifies the config presets for the server and other stuff
=> Config Presets

Resources/Prototypes/Entities/_StationWare/Objects/Weapons/baseball_bat.yml
=> buff knockback

Content.Server/_StationWare/Challenges/Modifiers/Components/SpawnEntityModifierComponent.cs, Content.Server/_StationWare/Challenges/Modifiers/Systems/WinningMarkerModifierSystem.cs, Content.Server/_StationWare/GameRules/StationWareRuleSystem.cs, Resources/Locale/en-US/game-ticking/game-presets/preset-stationware.ftl, Resources/Prototypes/Challenges/challenges.yml
Closes #77 
Closes #73 
Closes #69 
**Media**
**Changelog**
no cl no fun
=> bunch of random tweaks

Content.Server/_StationWare/Challenges/ChallengePrototype.cs, Content.Server/_StationWare/Challenges/StationWareChallengeComponent.cs, Content.Server/_StationWare/Challenges/StationWareChallengeSystem.cs
rain you fool
**Media**
**Changelog**
no cl no fun
=> Add support for challenge tags and infinite duration

Content.Server/_StationWare/Challenges/Modifiers/Components/HighestPriceWinModifierComponent.cs, Content.Server/_StationWare/Challenges/Modifiers/Systems/HighestPriceWinModifierSystem.cs, Resources/Locale/en-US/_StationWare/ware-events/challenges.ftl, Resources/Prototypes/Challenges/challenges.yml
Closes #83 
pick up valuables
get money
win
ez
**Media**
**Changelog**
:cl:
- add: Added Get Rich challenge.
=> Get Rich Challenge

Content.Server/_StationWare/GameRules/StationWareRuleSystem.cs
**Media**
**Changelog**
no cl no fun
=> fix challenge-per-round > total-challenges crashing game

Resources/Locale/en-US/_StationWare/ware-events/challenges.ftl, Resources/Prototypes/Challenges/challenges.yml, Resources/Prototypes/Entities/_StationWare/Objects/Weapons/fire_extingusher.yml, Resources/Prototypes/Reagents/_StationWare/toxins.yml
New acid trip event :)
**Media**
I have not.
**Changelog**
:cl: PixelTK
- add: Acid trip event! Have fun :)
=> The acid burns

Content.Server/_StationWare/Challenges/Modifiers/Components/BuckledWinModifierComponent.cs, Content.Server/_StationWare/Challenges/Modifiers/Components/SpawnEntityModifierComponent.cs, Content.Server/_StationWare/Challenges/Modifiers/Systems/BuckledWinModifierSystem.cs, Content.Server/_StationWare/Challenges/Modifiers/Systems/SpawnEntityModifierSystem.cs, Resources/Locale/en-US/_StationWare/ware-events/challenges.ftl, Resources/Prototypes/Challenges/challenges.yml
Closes #85 
**Media**
**Changelog**
:cl:
- add: Added Musical Chairs
=> musical chairs

Content.Server/Polymorph/Systems/PolymorphedEntitySystem.cs
Closes #58 
**Media**
**Changelog**
no cl no fun
=> revert polymorph on round end

Resources/Locale/en-US/_StationWare/ware-events/challenges.ftl, Resources/Prototypes/Challenges/challenges.yml, Resources/Prototypes/Entities/_StationWare/Structures/explodingtile.yml
Closes #70 
**Media**
**Changelog**
no cl no fun
=> Winning Tiles

Resources/Prototypes/Entities/_StationWare/Structures/explodingtile.yml
=> Add a suffix to the exploding tiles

Content.Server/Body/Systems/BodySystem.cs, Content.Server/_StationWare/Mobs/DeleteOnDeathSystem.cs, Resources/Prototypes/Entities/Effects/puddle.yml
Closes #105 
i made an issue but it was a quick-ass fix
**Media**
**Changelog**
:cl:
- tweak: Blood and organs will no longer litter the entire map.
=> cleanup blood and organs

Tools/upstream_merge_tool.ps1
closes #88 and adds moony's upstream tool
=> Add the upstream merging tool

Content.Server/_StationWare/Challenges/Modifiers/Systems/FreezeModifierSystem.cs, Content.Server/_StationWare/Challenges/Modifiers/Systems/InteractionWinSystem.cs, Content.Server/_StationWare/Challenges/Modifiers/Systems/NonSolidStructuresModifierSystem.cs, Content.Server/_StationWare/Challenges/Modifiers/Systems/SpawnEntityModifierSystem.cs, Content.Server/_StationWare/Challenges/Modifiers/Systems/StayAliveModifierSystem.cs, Content.Server/_StationWare/Challenges/Modifiers/Systems/StayOnGridModifierSystem.cs, Content.Server/_StationWare/Challenges/Modifiers/Systems/WinningMarkerModifierSystem.cs, Content.Server/_StationWare/Challenges/StationWareChallengeSystem.Effects.cs, Content.Server/_StationWare/Challenges/StationWareChallengeSystem.cs, Content.Server/_StationWare/Mobs/DeleteOnDeathSystem.cs, Resources/Maps/dumbbell.yml, Resources/Maps/hydra.yml
entityqueryenumerator my beloved.
also forgor to fixgridatmos hydra and dumbbell
**Media**
**Changelog**
no cl no fun
=> cleanup code and fix maps

Content.Server/_StationWare/Challenges/Modifiers/Components/EquipClothingModifierComponent.cs, Content.Server/_StationWare/Challenges/Modifiers/Components/GodmodeModifierComponent.cs, Content.Server/_StationWare/Challenges/Modifiers/Components/SpawnEntityModifierComponent.cs, Content.Server/_StationWare/Challenges/Modifiers/Systems/EquipClothingModifierSystem.cs, Content.Server/_StationWare/Challenges/Modifiers/Systems/GodmodeModifierSystem.cs, Resources/Prototypes/Challenges/challenges.yml
adds a modifier for equiping clothing
adds a modifier for giving players godmode.
**Media**
**Changelog**
no cl no fun
=> Clothing modifier + godmode modifier

Content.Server/_StationWare/Mobs/DeleteOnDeathSystem.cs
**Media**
**Changelog**
:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!
=> fix deleteondeathsystem fails

Content.Client/_StationWare/ChallengeOverlay/ChallengeOverlay.cs, Content.Client/_StationWare/ChallengeOverlay/ChallengeOverlaySystem.cs, Content.Server/_StationWare/ChallengeOverlay/ChallengeOverlaySystem.cs, Content.Server/_StationWare/Challenges/StationWareChallengeSystem.cs, Content.Server/_StationWare/GameRules/StationWareRuleSystem.cs, Content.Shared/_StationWare/ChallengeOverlay/SharedChallengeOverlaySystem.cs, Resources/Locale/en-US/_StationWare/overlay.ftl
Couldn't pump out a challenge but I did crawl through UI hell so take this as a substitute
Day #2 of PR-ing something to stationware
=> StationWare Status Bars

Content.Client/_StationWare/ChallengeOverlay/ChallengeOverlay.cs, Content.Client/_StationWare/ChallengeOverlay/ChallengeOverlaySystem.cs, Content.Client/_StationWare/Points/PointSystem.cs, Content.Server/_StationWare/ChallengeOverlay/ChallengeOverlaySystem.cs, Content.Server/_StationWare/GameRules/StationWareRuleSystem.cs, Content.Server/_StationWare/Points/PointSystem.cs, Content.Shared/_StationWare/ChallengeOverlay/SharedChallengeOverlaySystem.cs, Content.Shared/_StationWare/Points/PointManagerComponent.cs, Content.Shared/_StationWare/Points/SharedPointSystem.cs, Resources/Locale/en-US/_StationWare/overlay.ftl
Closes #145
some changes
- text now scales with window correctly
- score in bottom left
- challenge announcement has black box
**Media**
**Changelog**
no cl no bot
=> BIG overlay overhaul

Resources/ConfigPresets/Build/development.toml, Resources/ConfigPresets/_StationWare/stationware.toml, Resources/Server Info/SW_Rules.txt
bleh
**Media**
**Changelog**
no cl no bot
=> Rule tweaks

.github/workflows/publish.yml
**Media**
**Changelog**
:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!
=> Why are we doing this twice

Resources/ConfigPresets/_StationWare/stationware.toml, Resources/Prototypes/Datasets/_StationWare/tips.yml
=> stationware tips

Content.Server/Shuttles/Components/ArrivalsBlacklistComponent.cs, Content.Server/Shuttles/Systems/ArrivalsSystem.cs, Resources/Prototypes/Entities/Objects/Devices/nuke.yml, Resources/Prototypes/Entities/Objects/Misc/dat_fukken_disk.yml, Resources/Prototypes/Entities/Structures/Storage/Closets/base_structureclosets.yml
trying to get the fuckin test to stop failing on my ass
**Media**
**Changelog**
:cl:
- add: Added fun!
- remove: Removed fun!
- tweak: Changed fun!
- fix: Fixed fun!
=> Moar upstream

Content.Server/_StationWare/Challenges/Modifiers/Components/ResetPositionModifierComponent.cs, Content.Server/_StationWare/Challenges/Modifiers/Systems/ResetPositionModifierSystem.cs, Content.Server/_StationWare/Challenges/StationWareChallengeSystem.cs, Content.Server/_StationWare/GameRules/StationWareRuleSystem.cs, Resources/Prototypes/Challenges/challenges.yml
adds a system to reset player position once a challenge ends.
basically so people stop getting stuck in walls during not-spleef.
**Media**
**Changelog**
xoxoxo with love from yo momma
=> stop people getting stuck in walls

Content.Server/Body/Systems/BodySystem.cs, Content.Server/_StationWare/Challenges/StationWareChallengeSystem.cs
incorporates latejoins into currently active challenges
also fixes a hellbug with gibbing not counting deaths properly.
**Media**
**Changelog**
no cl no bot
=> Fix permadeath once and for all

Content.Server/_StationWare/Challenges/StationWareChallengeSystem.cs
return -> continue
fuck me and these multiplayer-only bugs
**Media**
**Changelog**
no cl no fun
=> actually fix respawns

Resources/Prototypes/Entities/Mobs/Species/slime.yml, Resources/Prototypes/Reagents/_StationWare/toxins.yml
Acid is now fucking lethal
**Media**
https://user-images.githubusercontent.com/44417085/229606470-6cbbf4b2-3e52-41dd-9bd9-2a3662378592.mp4
**Changelog**
:cl: crazybrain
- fix: Acid hurts people
=> Acid ouchie

Content.Server/_StationWare/Challenges/StationWareChallengeSystem.cs, Content.Shared/Radio/RadioChannelPrototype.cs
- radios don't need servers
- latejoiners lose challenges by default
**Media**
**Changelog**
oaguh
=> small changes

Resources/Prototypes/Actions/types.yml
=> Scream cooldown lowered

.github/workflows/pr-changelogs.yml, Tools/log_changelog.py
python port of #176
:cl: eclips_e
- add: If you're reading this, the newly implemented changelog system should be working!
=> changelog script

.github/workflows/pr-changelogs.yml
:cl: eclips_e
- add: If you're reading this, the newly implemented changelog system should be working!
- add: And it took me multiple attempts to do so, I'm in tears.
=> i am sobbing

Resources/Maps/ChallengeMaps/beach.yml, Resources/Maps/ChallengeMaps/nostalgia.yml, Resources/Prototypes/Challenges/challenges.yml
https://media.discordapp.net/attachments/1077114087382716446/1098200429592068146/image.png
:cl: eclips_e
- add: Added a new match for the Shootout and the CM challenge.
=> Add the Nostalgia and Beach map

Content.Server/_StationWare/Challenges/ChallengePrototype.cs, Content.Server/_StationWare/Challenges/StationWareChallengeComponent.cs, Content.Server/_StationWare/Challenges/StationWareChallengeSystem.cs, Content.Server/_StationWare/GameRules/StationWareRuleSystem.cs, Content.Server/_StationWare/Points/PointSystem.cs, Resources/Locale/en-US/_StationWare/challenges.ftl, Resources/Locale/en-US/_StationWare/overlay.ftl, Resources/Prototypes/Challenges/boss.yml, Resources/Prototypes/tags.yml
Adds support for boss rounds.
**Media**
**Changelog**
:cl: eclips_e
- add: Added boss round support.
=> Boss rounds

Resources/Maps/split.yml, Resources/Prototypes/Maps/split.yml
yea uhh new map
**Media**
**Changelog**
:cl:
- add: New map, Split!
=> New Map - Split
